# TODO 固定値の設定
steps:
  # Build the api container image
  - name: "gcr.io/cloud-builders/docker"
    id: "api-build"
    args:
      [
        "build",
        "-f",
        "./api/.docker/Dockerfile.dev",
        "--build-arg",
        "APP_PATH=/app_root/api",
        "-t",
        "asia-northeast1-docker.pkg.dev/md-docs-dev/md-docs-dev/api:latest",
        ".",
      ]
  # Build the frontend container image
  # - name: "gcr.io/cloud-builders/docker"
  #   id: "client-build"
  #   waitFor: ["-"]
  #   args:
  #     [
  #       "build",
  #       "-f",
  #       "./client/.docker/Dockerfile.dev",
  #       "--build-arg",
  #       "APP_PATH=/app_root/client",
  #       "-t",
  #       "asia-northeast1-docker.pkg.dev/md-docs-dev/md-docs-dev/client:latest",
  #       ".",
  #     ]
  # Push the api container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/md-docs-dev/md-docs-dev/api:latest",
      ]
  # Push the client container image to Container Registry
  # - name: "gcr.io/cloud-builders/docker"
  #   waitFor: ["client-build"]
  #   args:
  #     [
  #       "push",
  #       "asia-northeast1-docker.pkg.dev/md-docs-dev/md-docs-dev/client:latest",
  #     ]
images:
  - "asia-northeast1-docker.pkg.dev/md-docs-dev/md-docs-dev/api:latest"
  - "asia-northeast1-docker.pkg.dev/md-docs-dev/md-docs-dev/client:latest"
options:
  logging: "NONE"
